# Generated by Django 4.1.3 on 2022-11-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_user_first_joined_user_validation_token_issued"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="require_validation",
            field=models.BooleanField(default=True),
        ),
    ]
