# Generated by Django 4.1.1 on 2022-09-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="accountcategory",
            name="supercategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="account_management.accountcategory",
            ),
        ),
    ]
