# Generated by Django 4.1.1 on 2022-09-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_management", "0003_remove_accountcategory_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountcategory",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
