# Generated by Django 4.1.2 on 2022-10-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_management", "0003_ledger_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
