# Generated by Django 4.1.3 on 2022-11-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_management", "0005_journal_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="notes",
            new_name="note",
        ),
    ]
